[package]
name = "smallest_divisible_1_through_20"
version = "0.1.0"
authors = ["ploiu <ploiu415@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
